# Generated by Django 5.0.7 on 2024-07-17 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='guests',
            field=models.IntegerField(),
        ),
    ]
